### ISSUE TITLE
listReceivers throws StatusCodeError: 500

### ISSUE THREAD

**Issue by 22h49** [Mati365/librus-api#16]
Po invokowaniu
`client.authorize('*******', '*******').then(
client.inbox.listReceivers("nauczyciel").then(data => {console.log(data)})
 )`
otrzymuje
 `Unhandled rejection StatusCodeError: 500 - ""
    at new StatusCodeError (C:\Users\nate2463\Desktop\nwd-rel-zwln\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\nate2463\Desktop\nwd-rel-zwln\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\nate2463\Desktop\nwd-rel-zwln\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\nate2463\Desktop\nwd-rel-zwln\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:498:23)
    at Request.<anonymous> (C:\Users\nate2463\Desktop\nwd-rel-zwln\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:498:23)
    at IncomingMessage.<anonymous> (C:\Users\nate2463\Desktop\nwd-rel-zwln\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:498:23)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`
Wszystko inne działa

**Comment by Mati365** [comment]
Cześć, dzięki za issue. Niestety nie mam dostępu do librusa i nawet nie mam jak tego naprawić :( Być może zmieniony został adres tej podstrony bądź tez format argumentów w URLu, mógłbyś sprawdzić?

**Comment by nate2463** [comment]
Wysyłanie wiadomości też nie działa, sprawdzałem podstrona jest taka sama, ale z tego co widzę numery identyfikacje nauczycieli mają po 5 cyfr zamiast 4 wątpię żeby to na cokolwiek wpływało nazwy klucze w zapytaniach POST też są takie same

**Comment by nate2463** [comment]
Tutaj jest treść żądania POST z wiadomosci/2/5

`Content-Disposition: form-data; name="filtrUzytkownikow"

0
Content-Disposition: form-data; name="idPojemnika"


Content-Disposition: form-data; name="klasa_rada_rodzicow"

71512
Content-Disposition: form-data; name="szkolna_rada_rodzicow"

71512
Content-Disposition: form-data; name="adresat"

nauczyciel
Content-Disposition: form-data; name="zaznacz_wszystkie"

on
Content-Disposition: form-data; name="DoKogo[]"

2771836
Content-Disposition: form-data; name="DoKogo_hid[]"

2771836
Content-Disposition: form-data; name="temat"


Content-Disposition: form-data; name="tresc"


Content-Disposition: form-data; name="poprzednia"

5
Content-Disposition: form-data; name="fileStorageIdentifier"`

**Comment by nate2463** [comment]
A i warto zaznaczyć że jest tam taki klucz jak "requestkey", który usunąłem z powodów prywatności

**Comment by nate2463** [comment]
Librus zmienił działanie Oautha i wiadomości naprawię to i zrobię forka

**Comment by Mati365** [comment]
Dzięki, zrób potem pull-request i mergnę. Ludziom się przyda.

**Comment by DiaxManPl** [comment]
Mozna to już zamknąć
