### ISSUE TITLE
Error in version 2.8.0

### ISSUE THREAD

**Issue by Norbiros** [Mati365/librus-api#44]
```
/home/norbi/Development/RadioBON/RadioBON-API/node_modules/librus-api/lib/tools.js:15
cheerio.prototype.trim = function() {
                       ^

TypeError: Cannot set properties of undefined (setting 'trim')
    at Object.<anonymous> (/home/norbi/Development/RadioBON/RadioBON-API/node_modules/librus-api/lib/tools.js:15:24)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/norbi/Development/RadioBON/RadioBON-API/node_modules/librus-api/lib/resources/inbox.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/norbi/Development/RadioBON/RadioBON-API/node_modules/librus-api/lib/api.js:86:20
    at arrayEach (/home/norbi/Development/RadioBON/RadioBON-API/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/home/norbi/Development/RadioBON/RadioBON-API/node_modules/lodash/lodash.js:9410:14)
    at Librus._loadModules (/home/norbi/Development/RadioBON/RadioBON-API/node_modules/librus-api/lib/api.js:85:7)
    at new Librus (/home/norbi/Development/RadioBON/RadioBON-API/node_modules/librus-api/lib/api.js:32:10)
    at fetchLibrusData (/home/norbi/Development/RadioBON/RadioBON-API/utils.js:6:11)
    at Object.<anonymous> (/home/norbi/Development/RadioBON/RadioBON-API/utils.js:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)

Node.js v18.6.0
[nodemon] app crashed - waiting for file changes before starting...
```
Node: `v18.6.0`

**Comment by Mati365** [comment]
Downgrade do 2.7 pomaga czy nołp?

**Comment by Norbiros** [comment]
Nie istnieje wersja `2.7.0`. Jest tylko `2.6.0`... Ale tak, pomaga

**Comment by Mati365** [comment]
https://github.com/Mati365/librus-api/commit/19d29650c44d178ab316b3809aa2139a82130d1d obstawiam podbicie Cheerio, jesteś w stanie sprawdzić lokalnie czy po downgrade cheerio na wersji 2.8 pomaga?

**Comment by Norbiros** [comment]
Nie mam jak tego przetestować na szybko.... Możesz Ty?

**Comment by Mati365** [comment]
Opublikuje na wieczór, sprawdzę

**Comment by Mati365** [comment]
@Norbiros podbiłem wersję na 2.8.1, zobacz czy działa

**Comment by Norbiros** [comment]
Z tego co widzę co tak (przetestowałem większość funkcji, ale dopiero początek roku i nie ma ogłoszeń itp.)!

**Comment by Mati365** [comment]
Fantastycznie. Dzięki za poprawki! Jakbyś chciał rozbudować libkę to śmiało rób PRki, zamykam PRkę
